spring:
  application:
    name: zkfindclient
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
      discovery:
        register: false
      dependencies:
        service-zookeeper:
          required: true
#          path: service-zookeeper
          loadBalancerType: ROUND_ROBIN
server:
  port: 11001

#ribbon:
#  eager-load:
#    enabled: true
#    clients: zookeeper-discovery-server
