spring:
  application:
    name: feign_client
server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://server1:5555/eureka/,http://server2:5556/eureka/
feign:
  hystrix:
    enabled: true
