#spring:
#  zipkin:
#    base-url: http://localhost:9411
spring:
  application:
    name: mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: zhh
    password: zhh1026

server:
  port: 13001


mybatis:
  mapper-locations: classpath:shark/mybatis/mapper/*.xml
