server:
  port: 15003

#authserver: http://localhost:8080
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      clientId: testClient
#      clientSecret: testClient
#      accessTokenUri: ${authserver}/oauth/token
#      userAuthorizationUri: ${authserver}/oauth/authorize
#    resource:
#      userInfoUri: ${authserver}/user
#spring:
#  thymeleaf:
#    cache: false

#security:
#  oauth2:
#    client:
#      client-id: clientId
#      client-secret: clientSecret
#      scope: scope1, scope2, scope3, scope4
#      registered-redirect-uri: http://www.baidu.com
#
#spring:
#  security:
#    user:
#      name: admin
#      password: admin